# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Wed Apr 19 23:07:25 2017
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(500, 510)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.serialConnect_btn = QtGui.QPushButton(self.groupBox)
        self.serialConnect_btn.setObjectName(_fromUtf8("serialConnect_btn"))
        self.gridLayout_3.addWidget(self.serialConnect_btn, 0, 2, 1, 1)
        self.serialDisconnect_btn = QtGui.QPushButton(self.groupBox)
        self.serialDisconnect_btn.setObjectName(_fromUtf8("serialDisconnect_btn"))
        self.gridLayout_3.addWidget(self.serialDisconnect_btn, 1, 2, 1, 1)
        self.serialPortsList_cb = QtGui.QComboBox(self.groupBox)
        self.serialPortsList_cb.setObjectName(_fromUtf8("serialPortsList_cb"))
        self.gridLayout_3.addWidget(self.serialPortsList_cb, 0, 0, 2, 1)
        self.serialPortListRefresh_btn = QtGui.QPushButton(self.groupBox)
        self.serialPortListRefresh_btn.setObjectName(_fromUtf8("serialPortListRefresh_btn"))
        self.gridLayout_3.addWidget(self.serialPortListRefresh_btn, 0, 1, 2, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 3)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 3, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 1, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(10, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 2, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(10, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 2, 2, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setContentsMargins(10, -1, -1, -1)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.cmdMode_cb = QtGui.QComboBox(self.centralwidget)
        self.cmdMode_cb.setObjectName(_fromUtf8("cmdMode_cb"))
        self.cmdMode_cb.addItem(_fromUtf8(""))
        self.cmdMode_cb.addItem(_fromUtf8(""))
        self.cmdMode_cb.addItem(_fromUtf8(""))
        self.cmdMode_cb.addItem(_fromUtf8(""))
        self.cmdMode_cb.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.cmdMode_cb)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem4 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.formLayout_5 = QtGui.QFormLayout(self.groupBox_4)
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.nominalCurrent = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.nominalCurrent.setDecimals(1)
        self.nominalCurrent.setMaximum(5.0)
        self.nominalCurrent.setSingleStep(0.1)
        self.nominalCurrent.setObjectName(_fromUtf8("nominalCurrent"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.nominalCurrent)
        self.label_8 = QtGui.QLabel(self.groupBox_4)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_8)
        self.nominalTime = QtGui.QSpinBox(self.groupBox_4)
        self.nominalTime.setMinimum(1)
        self.nominalTime.setMaximum(99)
        self.nominalTime.setSingleStep(1)
        self.nominalTime.setObjectName(_fromUtf8("nominalTime"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.nominalTime)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_9)
        self.maintainCurrent = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.maintainCurrent.setDecimals(1)
        self.maintainCurrent.setMinimum(0.1)
        self.maintainCurrent.setMaximum(5.0)
        self.maintainCurrent.setSingleStep(0.1)
        self.maintainCurrent.setObjectName(_fromUtf8("maintainCurrent"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.maintainCurrent)
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_10)
        self.maintainTime = QtGui.QSpinBox(self.groupBox_2)
        self.maintainTime.setMinimum(10)
        self.maintainTime.setMaximum(990)
        self.maintainTime.setSingleStep(10)
        self.maintainTime.setObjectName(_fromUtf8("maintainTime"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.maintainTime)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.formLayout_4 = QtGui.QFormLayout(self.groupBox_3)
        self.formLayout_4.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_17 = QtGui.QLabel(self.groupBox_3)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_17)
        self.boostCurrent = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.boostCurrent.setDecimals(1)
        self.boostCurrent.setMinimum(0.1)
        self.boostCurrent.setMaximum(5.0)
        self.boostCurrent.setSingleStep(0.1)
        self.boostCurrent.setObjectName(_fromUtf8("boostCurrent"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.boostCurrent)
        self.boostTime = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.boostTime.setDecimals(1)
        self.boostTime.setMinimum(0.1)
        self.boostTime.setMaximum(9.9)
        self.boostTime.setSingleStep(0.1)
        self.boostTime.setObjectName(_fromUtf8("boostTime"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.boostTime)
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_12)
        self.horizontalLayout.addWidget(self.groupBox_3)
        spacerItem5 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.formLayout_3.setLayout(6, QtGui.QFormLayout.SpanningRole, self.horizontalLayout)
        self.currentRange_cb = QtGui.QComboBox(self.centralwidget)
        self.currentRange_cb.setObjectName(_fromUtf8("currentRange_cb"))
        self.currentRange_cb.addItem(_fromUtf8(""))
        self.currentRange_cb.addItem(_fromUtf8(""))
        self.currentRange_cb.addItem(_fromUtf8(""))
        self.currentRange_cb.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.FieldRole, self.currentRange_cb)
        self.currentProfile_cb = QtGui.QComboBox(self.centralwidget)
        self.currentProfile_cb.setObjectName(_fromUtf8("currentProfile_cb"))
        self.currentProfile_cb.addItem(_fromUtf8(""))
        self.currentProfile_cb.addItem(_fromUtf8(""))
        self.currentProfile_cb.addItem(_fromUtf8(""))
        self.currentProfile_cb.addItem(_fromUtf8(""))
        self.currentProfile_cb.addItem(_fromUtf8(""))
        self.currentProfile_cb.addItem(_fromUtf8(""))
        self.currentProfile_cb.addItem(_fromUtf8(""))
        self.currentProfile_cb.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.currentProfile_cb)
        self.currentFault_cb = QtGui.QComboBox(self.centralwidget)
        self.currentFault_cb.setObjectName(_fromUtf8("currentFault_cb"))
        self.currentFault_cb.addItem(_fromUtf8(""))
        self.currentFault_cb.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.currentFault_cb)
        self.microStep_cb = QtGui.QComboBox(self.centralwidget)
        self.microStep_cb.setObjectName(_fromUtf8("microStep_cb"))
        self.microStep_cb.addItem(_fromUtf8(""))
        self.microStep_cb.addItem(_fromUtf8(""))
        self.microStep_cb.addItem(_fromUtf8(""))
        self.microStep_cb.addItem(_fromUtf8(""))
        self.microStep_cb.addItem(_fromUtf8(""))
        self.microStep_cb.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.microStep_cb)
        self.fctMode_cb = QtGui.QComboBox(self.centralwidget)
        self.fctMode_cb.setObjectName(_fromUtf8("fctMode_cb"))
        self.fctMode_cb.addItem(_fromUtf8(""))
        self.fctMode_cb.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.fctMode_cb)
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_3.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_13)
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_3.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_14)
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_3.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_15)
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_3.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_16)
        self.maxSpeed = QtGui.QSpinBox(self.centralwidget)
        self.maxSpeed.setMinimum(100)
        self.maxSpeed.setMaximum(9900)
        self.maxSpeed.setSingleStep(100)
        self.maxSpeed.setObjectName(_fromUtf8("maxSpeed"))
        self.formLayout_3.setWidget(7, QtGui.QFormLayout.FieldRole, self.maxSpeed)
        self.fastDecay = QtGui.QSpinBox(self.centralwidget)
        self.fastDecay.setMaximum(15)
        self.fastDecay.setObjectName(_fromUtf8("fastDecay"))
        self.formLayout_3.setWidget(8, QtGui.QFormLayout.FieldRole, self.fastDecay)
        self.deadband = QtGui.QSpinBox(self.centralwidget)
        self.deadband.setMinimum(100)
        self.deadband.setMaximum(10090)
        self.deadband.setSingleStep(10)
        self.deadband.setObjectName(_fromUtf8("deadband"))
        self.formLayout_3.setWidget(9, QtGui.QFormLayout.FieldRole, self.deadband)
        self.filterTime = QtGui.QSpinBox(self.centralwidget)
        self.filterTime.setMaximum(7992)
        self.filterTime.setSingleStep(8)
        self.filterTime.setObjectName(_fromUtf8("filterTime"))
        self.formLayout_3.setWidget(10, QtGui.QFormLayout.FieldRole, self.filterTime)
        self.verticalLayout.addLayout(self.formLayout_3)
        self.gridLayout_2.addLayout(self.verticalLayout, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox.setTitle(_translate("MainWindow", "Serial COM configuration", None))
        self.serialConnect_btn.setText(_translate("MainWindow", "Connect", None))
        self.serialDisconnect_btn.setText(_translate("MainWindow", "Disconnect", None))
        self.serialPortListRefresh_btn.setText(_translate("MainWindow", "Refresh", None))
        self.label.setText(_translate("MainWindow", "Mode de commande :", None))
        self.cmdMode_cb.setItemText(0, _translate("MainWindow", "Horloge/Sens", None))
        self.cmdMode_cb.setItemText(1, _translate("MainWindow", "CW/CCW", None))
        self.cmdMode_cb.setItemText(2, _translate("MainWindow", "EnableCW/EnableCCW", None))
        self.cmdMode_cb.setItemText(3, _translate("MainWindow", "Consigne analogique/Sens", None))
        self.cmdMode_cb.setItemText(4, _translate("MainWindow", "Pilotage par PC", None))
        self.label_3.setText(_translate("MainWindow", "Config Fdc :", None))
        self.label_2.setText(_translate("MainWindow", "Micro pas :", None))
        self.label_4.setText(_translate("MainWindow", "Courant de défaut :", None))
        self.label_5.setText(_translate("MainWindow", "Profil de courant :", None))
        self.label_6.setText(_translate("MainWindow", "Gamme de courant :", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Nominal", None))
        self.label_7.setText(_translate("MainWindow", "Courant :", None))
        self.nominalCurrent.setSuffix(_translate("MainWindow", " A", None))
        self.label_8.setText(_translate("MainWindow", "Temps :", None))
        self.nominalTime.setSuffix(_translate("MainWindow", " ms", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Maintien", None))
        self.label_9.setText(_translate("MainWindow", "Courant :", None))
        self.maintainCurrent.setSuffix(_translate("MainWindow", " A", None))
        self.label_10.setText(_translate("MainWindow", "Temps :", None))
        self.maintainTime.setSuffix(_translate("MainWindow", " ms", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Boost", None))
        self.label_17.setText(_translate("MainWindow", "Courant :", None))
        self.boostCurrent.setSuffix(_translate("MainWindow", " A", None))
        self.boostTime.setSuffix(_translate("MainWindow", " ms", None))
        self.label_12.setText(_translate("MainWindow", "Temps :", None))
        self.currentRange_cb.setItemText(0, _translate("MainWindow", "0.2 - 1.9 A", None))
        self.currentRange_cb.setItemText(1, _translate("MainWindow", "0.2 - 2.4 A", None))
        self.currentRange_cb.setItemText(2, _translate("MainWindow", "0.3 - 3.1 A", None))
        self.currentRange_cb.setItemText(3, _translate("MainWindow", "0.5 - 4.9 A", None))
        self.currentProfile_cb.setItemText(0, _translate("MainWindow", "Total", None))
        self.currentProfile_cb.setItemText(1, _translate("MainWindow", "Sans boost", None))
        self.currentProfile_cb.setItemText(2, _translate("MainWindow", "Sans arrêt", None))
        self.currentProfile_cb.setItemText(3, _translate("MainWindow", "Sans boost et sans arrêt", None))
        self.currentProfile_cb.setItemText(4, _translate("MainWindow", "Sans maintien", None))
        self.currentProfile_cb.setItemText(5, _translate("MainWindow", "Sans maintien et sans boost", None))
        self.currentProfile_cb.setItemText(6, _translate("MainWindow", "Sans maintien et sans arrêt", None))
        self.currentProfile_cb.setItemText(7, _translate("MainWindow", "Sans maintien, sans boost et sans arrêt", None))
        self.currentFault_cb.setItemText(0, _translate("MainWindow", "Arrêt en défaut", None))
        self.currentFault_cb.setItemText(1, _translate("MainWindow", "Maintien en défaut", None))
        self.microStep_cb.setItemText(0, _translate("MainWindow", "Pas entier", None))
        self.microStep_cb.setItemText(1, _translate("MainWindow", "1/2 pas", None))
        self.microStep_cb.setItemText(2, _translate("MainWindow", "1/4 pas", None))
        self.microStep_cb.setItemText(3, _translate("MainWindow", "1/8 pas", None))
        self.microStep_cb.setItemText(4, _translate("MainWindow", "1/16 pas", None))
        self.microStep_cb.setItemText(5, _translate("MainWindow", "1/32 pas", None))
        self.fctMode_cb.setItemText(0, _translate("MainWindow", "Avec fin de course", None))
        self.fctMode_cb.setItemText(1, _translate("MainWindow", "Avec boost et maintien", None))
        self.label_13.setText(_translate("MainWindow", "Vitesse max :", None))
        self.label_14.setText(_translate("MainWindow", "Fast decay :", None))
        self.label_15.setText(_translate("MainWindow", "Seuil de déclenchement :", None))
        self.label_16.setText(_translate("MainWindow", "Temps d\'établissement :", None))
        self.maxSpeed.setSuffix(_translate("MainWindow", " pps", None))
        self.fastDecay.setSuffix(_translate("MainWindow", " µs", None))
        self.deadband.setSuffix(_translate("MainWindow", " mV", None))
        self.filterTime.setSuffix(_translate("MainWindow", " ms", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

